export const portafolios = [
    {
        id: 1,
        title: "Portfolio 1",
        description: "This is a description of the portfolio 1",
        image: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=870&q=80",
        url: "https://www.example.com",
        category: "Personal",
        tags: ["React", "Next.js", "Tailwind CSS", "TypeScript"],
    },
    {
        id: 2,
        title: "Portfolio 2",
        description: "This is a description of the portfolio 2",
        image: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=870&q=80",
        url: "https://www.example.com",
        category: "Personal",
        tags: ["React", "Next.js", "Tailwind CSS", "TypeScript"],
    },
    {
        id: 3,
        title: "Portfolio 3",
        description: "This is a description of the portfolio 3",
        image: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=870&q=80",
        url: "https://www.example.com",
        category: "Personal",
        tags: ["React", "Next.js", "Tailwind CSS", "TypeScript"],
    },
    {
        id: 4,
        title: "Portfolio 4",
        description: "This is a description of the portfolio 4",
        image: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=870&q=80",
        url: "https://www.example.com",
        category: "Personal",
        tags: ["React", "Next.js", "Tailwind CSS", "TypeScript"],
    },
    {
        id: 5,
        title: "Portfolio 5",
        description: "This is a description of the portfolio 5",        
        image: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=870&q=80",
        url: "https://www.example.com",
        category: "Personal",
        tags: ["React", "Next.js", "Tailwind CSS", "TypeScript"],
    },
]